#!/bin/bash

function echoCo {
    echo -e "\033[32m$@\033[0m"
}

set -e

echoCo 'npmfupgradeg'
        npmfupgradeg
echoCo 'pipfupgrade'
        pipfupgrade
echoCo 'brewfupgrade'
        brewfupgrade
