#!/bin/bash

function echoCo {
    echo -e "\033[32m$@\033[0m"
}

# export HOMEBREW_VERBOSE=1

set -e
# set -o xtrace

echoCo 'brew update -v'
        brew update -v
echoCo 'brew upgrade'
        brew upgrade
echoCo 'brew cleanup'
        brew cleanup
echoCo 'brew doctor'
        brew doctor

echo 'cd "$(brew --repo)" && git prune && git gc'
