#!/bin/bash

# https://superuser.com/questions/747884/how-to-write-a-script-that-accepts-input-from-a-file-or-from-stdin
[ $# -ge 1 -a -f "$1" ] && input="$1" || input="-"
cat $input | tee /tmp/myshell.$(basename "$0")
