#!/bin/bash

function echoCo {
    echo -e "\033[32m${@}\033[0m"
}

function echoMe {
    echo -e "\033[35m${@}\033[0m"
}

echoMe ${@}

echo ''

for var in "${@}"
do
    if [ ! "${1}" = "${var}" ]; then
        echo '↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧↧'
        # echoCo "icdiff --line-numbers  ${1}   ${var}"
                  icdiff --line-numbers "${1}" "${var}"
        echo '↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥↥'
        echo ''
    fi
done
