#!/bin/sh

if [ ! "$1" = '-delete' ]
then
    echo 'add -delete to delete'
fi

set -o xtrace

find . \
-name '.*' \
-mindepth 2

find . \
-type d \
-empty \
! -path "*/\.git/*" \
! -path "*/node_modules/*" \
! -path "*/components/*" \
"$@"
