#!/bin/bash

output=$(
find $@ -type f \
! -path "*/\.git/*" \
! -path "*/components/*" \
! -path "*/node_modules/*" \
! -path "*/target/*" \
| sed 's/ /=/g' | rev | sort | rev)

maxLength=0;
for key in ${output};
do
    if [ ${#key} -gt $maxLength ]
    then
        maxLength=${#key}
    fi
done

for key in ${output};
do
    printf "%*s\n" "${maxLength}" "${key}"
done
