#! /bin/bash


function echoCo {
    echo -e "\033[32m$@\033[0m"
}


echoCo 'git pull'
        git pull


echoCo 'git submodule init'
        git submodule init


echoCo 'git submodule update'
        git submodule update


# echoCo 'git submodule update --recursive --remote'
#         git submodule update --recursive --remote
