#!/usr/bin/env node

const childProcess = require('child_process');
const path = require('path');

let filePath = path.resolve(process.cwd(), process.argv[2]);
let allData = require(filePath);

const capitalizeFirstLetter = (string) => {
  // return string.charAt(0).toUpperCase() + string.slice(1);
  return string;
};

Object.keys(allData).forEach(function (key) {
  let command = `echo '${JSON.stringify(allData[key])}' | ~/workspacego/bin/gojson -fmt=json -name=${capitalizeFirstLetter(key)} -subStruct=true -tags=json,form,bson | grep -v 'package main'` + ' | sed -e "s/\\`$/ binding:\\"required\\"\\`/g"';
  // console.log(command);
  childProcess.execSync(command, {stdio: [0, 1, 2]});
});
