#!/bin/bash

# https://docs.gradle.org/current/userguide/build_init_plugin.html

set -e

projectName=$1

if [ -d ${projectName} ]
then
    echo "${projectName} exists"
    exit 1
fi

mkdir ${projectName}
cd ${projectName}
gradle init \
--type java-application \
--project-name ${projectName} \
--package ${projectName} \
--dsl groovy \
--test-framework testng

touch README.md
