#!/bin/sh

# \s 匹配任何空白字符，包括空格、制表符、换页符等等。等价于 [ \f\n\r\t\v]。
# *  匹配前面的子表达式零次或多次。要匹配 * 字符，请使用 \*。
# .  匹配除换行符 \n 之外的任何单字符。要匹配 . ，请使用 \. 。

# not work for tab
# grep '\t'

# work for tab
# grep -P '\t'
# grep $'\t'

# case "$OSTYPE" in
#   solaris*)
#     ;;
#   darwin*)
#     grep    '^\s*[^# \t].*$' $@
#     ;;
#   linux*)
#     grep -P '^\s*[^# \t].*$' $@
#     ;;
#   bsd*)
#     ;;
#   msys*)
#     ;;
#   *)
#     ;;
# esac


# grep -v '^#' $@ | grep -v '^$'

grep -v -n '^#' $@ | grep -v '^[1-9][0-9]*:$'
