#!/bin/bash

totalLineCount=`wc -l $1 | awk '{print $1}'`

awk -v totalLineCount="$totalLineCount" '
BEGIN {
  print "[";
}

{
  # print typeof(FNR);
  # print typeof(totalLineCount);
  if (FNR<totalLineCount) {
    printf("  %s,\n", $0);
  } else {
    printf("  %s\n", $0);
  }
}

END {
  print "]";
}
' $1
