#!/bin/sh

# </dev/null
# https://github.com/ggreer/the_silver_searcher/issues/943

mainClassName=$1

if [ "$#" -eq 0 ]
then
    filePath=$(ag 'public static void main' -H -G 'java$' ./src </dev/null | head -n 1)
    echo "filePath ${filePath}"
    mainClassName=$(echo ${filePath} | sed -e "s/src\/main\/java\///g")
    echo "mainClassName ${mainClassName}"
    mainClassName=$(echo ${mainClassName} | sed -e "s/.java//g")
    echo "mainClassName ${mainClassName}"
    mainClassName=$(echo ${mainClassName} | sed -e "s/\//\./g")
    echo "mainClassName ${mainClassName}"
fi

echo mvn clean compile exec:java -Dexec.cleanupDaemonThreads=false -Dexec.mainClass=${mainClassName}
     mvn clean compile exec:java -Dexec.cleanupDaemonThreads=false -Dexec.mainClass=${mainClassName}
