#!/bin/bash


set -e


artifactId=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
groupId=$(   mvn help:evaluate -Dexpression=project.groupId    -q -DforceStdout)
version=$(   mvn help:evaluate -Dexpression=project.version    -q -DforceStdout)

echo "artifactId ${artifactId}"
echo "groupId    ${groupId}"
echo "version    ${version}"

# clean & package
mvn clean package -Dmaven.test.skip=true -DfailIfNoTests=false

# install
mvn install:install-file -Dfile=target/${artifactId}-${version}.jar         -DgroupId=${groupId} -DartifactId=${artifactId} -Dversion=${version} -Dpackaging=jar
mvn install:install-file -Dfile=target/${artifactId}-${version}-sources.jar -DgroupId=${groupId} -DartifactId=${artifactId} -Dversion=${version} -Dpackaging=jar -Dclassifier=sources
mvn install:install-file -Dfile=pom.xml                                     -DgroupId=${groupId} -DartifactId=${artifactId} -Dversion=${version} -Dpackaging=pom
