#!/bin/bash



DartifactId=$1

DgroupId=com.fred.app
if [ $# -eq 2 ]; then
  DgroupId=$2
fi

mvn \
archetype:generate \
-DgroupId=$DgroupId \
-DartifactId=$DartifactId \
-DarchetypeArtifactId=maven-archetype-webapp \
-DinteractiveMode=false \
&& \
mkdir -p $1/src/main/java \
&& \
mkdir -p $1/src/test/java \
&& \
touch $1/.gitignore
