#! /bin/bash

#https://maven.apache.org/guides/introduction/introduction-to-archetypes.html

DartifactId=$1

DgroupId=com.fred.app
if [ $# -eq 2 ]; then
  DgroupId=$2
fi

mvn \
archetype:generate \
-DgroupId=$DgroupId \
-DartifactId=$DartifactId \
-DarchetypeArtifactId=maven-archetype-quickstart \
-DinteractiveMode=false
