#!/bin/bash


set -e


# mvn clean org.apache.tomcat.maven:tomcat7-maven-plugin:2.2:run -Dmaven.tomcat.path='/' -Dmaven.tomcat.port=$1

which xpath > /dev/null
if [ $? -ne 0 ]; then
    echo 'xpath not exist'
    echo 'ubuntu'
    echo 'sudo apt-get update -y && sudo apt-get install -y libxml-xpath-perl'
    exit 1
fi

which xmlstarlet > /dev/null
if [ $? -ne 0 ]; then
    echo 'xmlstarlet not exist'
    echo 'ubuntu'
    echo 'sudo apt-get update -y && sudo apt-get install -y xmlstarlet'
    exit 1
fi


mvn -U clean compile war:exploded

shutdownPort=8005
httpPort=8080
AJPPort=8009

if [ $# -eq 1 ]
  then
    httpPort=$1
fi
shutdownPort=$(($httpPort-1000))
AJPPort=$(($httpPort+1000))

# ls ./target
# read -p 'build_finalName: ' build_finalName
case "$OSTYPE" in
  solaris*)
    echo "SOLARIS"
    exit 1
    ;;
  darwin*)
    echo "OSX"
    build_finalName=$(xpath pom.xml '/project/profiles/profile/activation[contains(activeByDefault, 'true')]/../build/finalName/text()'         2>/dev/null)
    ;;
  linux*)
    echo "LINUX"
    build_finalName=$(xpath -e      '/project/profiles/profile/activation[contains(activeByDefault, 'true')]/../build/finalName/text()' pom.xml 2>/dev/null)
    ;;
  bsd*)
    echo "BSD"
    exit 1
    ;;
  msys*)
    echo "WINDOWS"
    exit 1
     ;;
  *)
    echo "unknown: $OSTYPE"
    exit 1
    ;;
esac


echo 'build_finalName:' ${build_finalName}
echo 'shutdownPort:' ${shutdownPort}
echo 'httpPort:' ${httpPort}
echo 'AJPPort:' ${AJPPort}


export CATALINA_HOME="/opt/tomcat-8.0.53"
export CATALINA_BASE="$(pwd)/target/${build_finalName}"


if [ ! -d "${CATALINA_BASE}/temp" ]
then
    mkdir "${CATALINA_BASE}/temp"
fi


if [ ! -d "${CATALINA_BASE}/conf" ]
then
    cp -r "${CATALINA_HOME}/conf" "${CATALINA_BASE}/conf"
fi


cat "${CATALINA_HOME}/conf/server.xml" | \
xmlstarlet edit --delete "//comment()" | \
xmlstarlet edit --update "/Server[@port='8005']/@port"                   --value "${shutdownPort}" | \
xmlstarlet edit --update "/Server/Service/Connector[@port='8080']/@port" --value "${httpPort}" | \
xmlstarlet edit --update "/Server/Service/Connector[@port='8009']/@port" --value "${AJPPort}" \
> "${CATALINA_BASE}/conf/server.xml"

# xpath "${CATALINA_BASE}/conf/server.xml" "/Server/Service/Connector"
# xpath "${CATALINA_BASE}/conf/server.xml" "/Server/Service/Connector[@port=\"${port}\"]/@port"


if [ ! -d "${CATALINA_BASE}/conf/Catalina/localhost" ]
then
    mkdir -p "${CATALINA_BASE}/conf/Catalina/localhost"
fi
echo "<Context path=\"\" docBase=\"${CATALINA_BASE}\" />" > "${CATALINA_BASE}/conf/Catalina/localhost/ROOT.xml"


${CATALINA_HOME}/bin/catalina.sh run
