#!/bin/bash

function echoCo {
    echo -e "\033[32m$@\033[0m"
}

# export HOMEBREW_VERBOSE=1

set -e
# set -o xtrace

echoCo 'npm-check    -g --skip-unused --update-all'
        npm-check    -g --skip-unused --update-all
echoCo 'npm-check    -g --skip-unused'
        npm-check    -g --skip-unused