#!/usr/bin/env node

let ip = process.argv[2];
// ip = '127.0.0.1';

const chalk = require('chalk');

const padLeft = (content, length, padding) => {
  return (new Array(length - content.length + 1).join(padding) + content);
};

const getBinaryString = (n) => {
  n = parseInt(n, 10);
  let binaryString = n.toString(2);
  binaryString = padLeft(binaryString, 8, '0');
  return binaryString;
};

const highlightChar = (content, hChar) => {
  let highlightContent = '';
  for (let char of content) {
    if (char === hChar) {
      char = chalk.red(char);
    }
    highlightContent += char;
  }
  return highlightContent;
};

let ipComponents = ip.split('.');
let ipOrigin = '';
let ipBinary = '';
for (let i = 0; i < ipComponents.length; i++) {
  let ipComponent = ipComponents[i];

  ipOrigin += padLeft(ipComponent, 8, ' ') + (i === ipComponents.length - 1 ? '' : '.');
  ipBinary += highlightChar(getBinaryString(ipComponent), '1') + (i === ipComponents.length - 1 ? '' : '.');
}
console.log(ipOrigin);
console.log(ipBinary);
