#!/bin/bash

set -e

set -o xtrace

args="$@"


              /usr/local/bin/pip3   --version
/bin/bash -c "/usr/local/bin/pip3   ${args}"
echo         "------------------------------------------------------------------------"


#               /usr/local/bin/pip    --version
# /bin/bash -c "/usr/local/bin/pip    ${args}"
# echo         "------------------------------------------------------------------------"


#               /usr/local/opt/python/libexec/bin/pip   --version
# /bin/bash -c "/usr/local/opt/python/libexec/bin/pip   ${args}"
# echo         "------------------------------------------------------------------------"
