#!/bin/bash

# https://gist.github.com/jolbax/cd2c63c0249f8595917b831425ac765a

if [ $# -ne 2 ] ; then
  echo "Usage: ssh-add-pass keyfile passfile"
  exit 1
fi

# the current shell will get the variables for other commands to inherit.
# eval $(ssh-agent)
pass=$(cat $2)

expect << EOF
  spawn ssh-add $1
  expect "Enter passphrase"
  send "$pass\r"
  expect eof
EOF
