#!/bin/sh

grepResult=$(tmux ls | grep "^$1:" | cut -d":" -f1)

if [ ${#grepResult} == 0 ]; then
    echo "start $1"
    
    nohup tmuxinator start $1 >/dev/null 2>&1 &

    sleep 8
else
    echo "$1 has started"
fi

tmux ls

tmux -CC attach -t $1