#!/bin/bash

# https://stackoverflow.com/questions/13570327/shell-script-deleting-a-substring
# http://tldp.org/LDP/abs/html/parameter-substitution.html

# foo=${foo#$prefix}
# foo=${foo%$suffix}

function echoCo {
    echo -e "\033[32m${@}\033[0m"
}

SESSIONNAME=${1%.yml}

grepResult=$(tmux ls | grep "^$SESSIONNAME:" | cut -d":" -f1)

if [ ${#grepResult} == 0 ]; then
    echo "start $SESSIONNAME"

    echoCo "nohup tmuxinator start $SESSIONNAME >/dev/null 2>&1 &"
            nohup tmuxinator start $SESSIONNAME >/dev/null 2>&1 &

    sleep 12
else
    echo "$SESSIONNAME has started"
fi

echoCo "tmux ls"
        tmux ls

echoCo "tmux -CC attach -t $SESSIONNAME"
        tmux -CC attach -t $SESSIONNAME
