#!/bin/bash

function echoEr {
    echo -e "\033[31m$@\033[0m"
}

# export XMLLINT_INDENT="    "

xmllint --format $1 > /tmp/xmllinttmp.xmllint

if [ $? -eq 0 ]; then
    cp /tmp/xmllinttmp.xmllint $1
else
    echoEr 'format failed'
fi

# emacs: 1
# C-x h C-u M-| xmllint --format - RET

# emacs: 2
# M-| ls
# M-| xmlpretty pom.xml
# M-x revert-buffer
# C-x h M-x indent-region
