#!/bin/bash

function echoEr {
    echo -e "\033[31m$@\033[0m"
}

# export XMLLINT_INDENT="    "

xmllint --format $1 > /tmp/xmllinttmp.xmllint

if [ $? -eq 0 ]; then
    cp /tmp/xmllinttmp.xmllint $1
else
    echoEr 'format failed'
fi

# emacs 
# M-| ls
# M-| xmllint --format pom.xml

# M-| xmlpretty        pom.xml
